---
title: "R.class.problem.set.3"
author: "Jay Baker"
date: "04/11/2015"
output: html_document
---
```{r}
library(ggplot2)
data(diamonds)
```

```{r}
summary(diamonds)
str(diamonds)
```

```{r}
qplot(x=price, data=diamonds, color=I('black'), 
  fill=I('#F79420')) +
  scale_x_continuous(breaks=seq(0,19000,1000), lim=c(0,19000))
summary(diamonds$price)
```
The mean is 3933 and the median is 2401. There is a big spike around $1000. There is a reasonably long tail. The max is 18820.

```{r}
length(subset(diamonds, price < 500)$price)
length(subset(diamonds, price < 250)$price)
length(subset(diamonds, price >= 15000)$price)
```

Explore the largest peak
```{r}
qplot(x=price, data=diamonds, color=I('black'), 
  fill=I('#F79420'), binwidth=1) +
  scale_x_continuous(breaks=seq(0,1500,100), lim=c(0,1500))
qplot(x=price, data=diamonds, color=I('black'), 
  fill=I('#F79420'), binwidth=100) +
  scale_x_continuous(breaks=seq(0,1500,100), lim=c(0,1500))
```

Diamond prices by cut
```{r}
qplot(x=price, data=diamonds, color=I('black'), 
  fill=I('#F79420')) +
  facet_wrap(~cut) +
  scale_x_continuous(breaks=seq(0,19000,1000), lim=c(0,19000))
```

```{r}
levels(diamonds$cut)
by(diamonds$price, diamonds$cut, summary) # notice how summary rounds to nearest 10
by(diamonds$price, diamonds$cut, max)
by(diamonds$price, diamonds$cut, min)
```

```{r}
qplot(x = price, data = diamonds) + facet_wrap(~cut, scales="free_y")
```

```{r}
# Create a histogram of price per carat
# and facet it by cut.
qplot(x = price/carat, data = diamonds, 
      ylab="Count", xlab="Price per Carat (log10)", binwidth=0.05) + 
  scale_x_log10() +
  facet_wrap(~cut, scales="free_y")
```

Price Box Plots
```{r}
str(diamonds$clarity)
by(diamonds$price, diamonds$clarity, summary)
qplot(x=clarity, y=price, data=diamonds, 
      geom='boxplot')
```

Interquartile Range - IQR
```{r}
str(diamonds$color)
levels(diamonds$color)
by(diamonds$price, diamonds$color, summary)
IQR(subset(diamonds, color == 'D')$price)
IQR(subset(diamonds, color == 'J')$price)
```

Price per Carat Box Plots by Color
```{r}
str(diamonds$color)
by(diamonds$price, diamonds$color, summary)
qplot(x=color, y=price/carat, data=diamonds, 
      geom='boxplot')
```

Carat Frequency Polygon
```{r}
qplot(x=carat, 
      data=diamonds,
      xlab="Carat",
      ylab="Count of diamonds with that carat",
      binwidth=.01, 
      geom='freqpoly')
```

Gapminder data
Labor force to population comparison.
```{r}
setwd('/home/jay/classes/R.class')
library(tidyr)
df <- read.csv('Gapminder.labor.to.population.csv', header=T, check.names=F)
names(df)
head(df)
newdf = gather(df, 'year', 'ratio', 2:ncol(df))
names(newdf)
head(newdf)
tail(newdf)
qplot(x=ratio, 
      data=newdf,
      xlab="Percent Labor Force",
      binwidth=1) +
  facet_wrap(~year)
data1997 <- subset(newdf, year == 1997)
data2007 <- subset(newdf, year == 2007)
summary(data1997)
summary(data2007)
```

Birthdays
```{r}
#install.packages('lubridate')
library(lubridate)
df <- read.csv('birthdaysExample.csv', header=T, check.names=F)
df$formattedDates <- as.Date(df$dates, format='%m/%d/%y')
head(df)
qplot(x=formattedDates, 
      data=df,
      xlab="Date",
      ylab="Count of birthdays",
      binwidth=1)

df$month <- month(df$formattedDates)
df$day <- day(df$formattedDates)
summary(df)
table(df[,c("month","day")])

```


